feat: use Lighthouse workflow from Jake

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -1,17 +1,31 @@
-name: Audit pull request
-on:
-  status
+name: Lighthouse
+
+on: pull_request
+
 jobs:
-  audit:
+  build:
     runs-on: ubuntu-latest
-    if: github.event.context == 'netlify/deploy-preview' && github.event.state == 'success'
+
     steps:
-      - name: Audit Netlify deploy preview
-        uses: jakejarvis/lighthouse-action@master
+      - uses: actions/checkout@v1
+      - name: Use Node.js 12.x
+        uses: actions/setup-node@v1
         with:
-          netlify_site: 'keen-roentgen-cafcb7.netlify.com'
-          url: 'https://deploy-preview-[[PR_NUMBER]]--[[NETLIFY_SITE]].netlify.com'
-      - uses: actions/upload-artifact@master
+          node-version: 12.x
+      - name: Install
+        run: |
+          yarn
+      - name: Build
+        run: |
+          yarn build
+      - name: Waiting for 200 from the Netlify Preview
+        uses: jakepartusch/wait-for-netlify-action@v1
+        id: waitFor200
         with:
-          name: report
-          path: './report'
+          site_name: 'joeprevite'
+      - name: Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.waitFor200.outputs.url }} || echo "LHCI failed!"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
